CREATE DATABASE `BlogDB` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE BlogDB;
CREATE TABLE Publishers (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PUBLISHER_NAME VARCHAR(255) UNIQUE
);
CREATE TABLE Authors (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LAST_NAME VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    FACEBOOK VARCHAR(255),
    INSTAGRAM VARCHAR(255),
    YOUTUBE VARCHAR(255),
    TIKTOK VARCHAR(255),
    X VARCHAR(255)
);
CREATE TABLE Articles (
     ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    AUTHOR_ID INT UNSIGNED NOT NULL,
    PUBLISHER_ID INT UNSIGNED NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    SUBTITLE VARCHAR(255),
    DATE_CREATED DATETIME NOT NULL,
    DATE_PUBLISHED DATETIME,
    READ_TIME TIME,
    DATE_MODIFIED DATETIME NOT NULL,
    IS_PUBLISHED TINYINT(1) NOT NULL,
    URL_SLUG_FOR_RTF VARCHAR(255) NOT NULL,
    CLICKS INT UNSIGNED NOT NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES Authors(ID),
    FOREIGN KEY (PUBLISHER_ID) REFERENCES Publishers(ID)
);
CREATE TABLE ArticleImages (

    ID INT UNSIGNED NOT NULL,
    ARTICLE_ID INT UNSIGNED NOT NULL,
    COLLLECTION_NAME VARCHAR(255) NOT NULL,
    FOREIGN KEY ( IMAGE_ID) REFERENCES IMAGES(ID),
    FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES(ID)
);
CREATE TABLE Images (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    IMAGE_NAME VARCHAR(255) NOT NULL,
    URL_SLUG VARCHAR(255) NOT NULL,
    IMAGE_DESCRIPTION VARCHAR(255)
);